# /docker-compose.yml
version: '3.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=dawooddilawar.com
      - LETSENCRYPT_HOST=dawooddilawar.com
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - proxy-network
      - internal-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - internal-network
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network
    # Note: healthcheck removed as it's not supported in 3.3
    restart: always

volumes:
  postgres_data:

networks:
  proxy-network:
    external: true
  internal-network:
    internal: true