# .github/workflows/backend-deploy.yml
name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/doublew/projects/portfolio-chat
            git pull
            cd backend
            # Build new container without stopping the old one
            docker build -t portfolio-chat-backend:new .
            # Gracefully stop old container and start new one
            docker compose stop backend
            # Update the image in docker-compose
            sed -i 's|portfolio-chat_backend|portfolio-chat-backend:new|' docker-compose.yml
            docker compose up -d backend