# .github/workflows/frontend-deploy.yml
name: Frontend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/doublew/projects/portfolio-chat
            git pull
            cd frontend
            # Build new container without stopping the old one
            docker build -t portfolio-chat-frontend:new .
            # Stop old container and start new one
            docker compose stop frontend
            # Update the image in docker-compose
            sed -i 's|portfolio-chat_frontend|portfolio-chat-frontend:new|' docker-compose.yml
            docker compose up -d frontend